spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/tr
    username: postgres
    password: sopra*
ldap:
  url: ldap://ptx.ldap-ad.dmsi.corp.sopra:3268/DC=emea,DC=msad,DC=sopra
  browsing:
    userDN: CN=svc Cacp,OU=Sopra FR,OU=Service Accounts,DC=emea,DC=msad,DC=sopra
    password: Czam2Out!
  users:
    base: OU=FR,OU=users,OU=Sopragroup,OU=UsersEmea
    search: sAMAccountName={0}
  groups:
    base: OU=Internal,OU=Distribution lists,OU=UsersEmea
    search: member={0}
  roles:
    admin: Sopra TMA Cacp PM
    user: Sopra TMA Cacp Activite
  attributes:
    fisrtName: givenname
    lastName: sn
    mail: mail
    location: l
    department: department